### PR TITLE
fix(docs): repair Wolf TeX notation builds

### LINKED ISSUE #392: Wolf Corollary 6.7: source-general weighted fixed-point star-algebra
## Source

Wolf, *Quantum Channels & Operations: Guided Tour*, Chapter 6, Corollary 6.7; local source `Notes/WolfNoteTexSource/ch06_spectral_properties.tex`, lines 1497--1510.

Parent tracker: #39. Chapter tracker: #42.

## Exact source statement

Let `T : M_d(ℂ) → M_d(ℂ)` be positive and trace preserving, and assume that its trace adjoint `T*` satisfies Wolf's Schwarz inequality (5.2). For every maximum-rank stationary density matrix `ρ`, the set

`ρ⁻¹ᐟ² 𝓕_T ρ⁻¹ᐟ²`

is a star algebra, where the inverse is taken on `supp(ρ)`.

Wolf presents this as an immediate consequence of Theorem 6.14: in the density-block form of `𝓕_T`, conjugation by the support inverse square root removes the positive-definite density factors and leaves a direct sum of full matrix algebras.

## Existing infrastructure and restriction

- `IsPositiveMap.exists_fixedPoints_densityBlocks_with_zero` already formalizes Wolf Theorem 6.14 under the source hypotheses.
- The maximum stationary-support and support-compression APIs are source-general.
- `Kraus.weightedFixedPointsStarSubalgebra`, `Kraus.weightedCornerFixedPointsStarSubalgebra`, and the maximal-rank transport results are useful specializations, but their Kraus-family hypotheses assume complete positivity and therefore do not by themselves formalize the printed corollary.
- The restriction is recorded in `docs/paper-gaps/wolf_cor67_maximal_support_restriction.tex`.

Do not introduce a parallel notion of fixed point, support projection, square root, or corner algebra.

## Required proof route

Follow the source: use the source-general Theorem 6.14 density-block decomposition, identify the support inverse square root blockwise, and obtain the direct-sum matrix star algebra. Reuse the existing maximum-rank support results to pass from the canonical maximal-support fixed point to every maximum-rank stationary density. A different proof may be used for a small auxiliary identity, but the headline proof and documentation must retain this Theorem 6.14 route.

## Acceptance criteria

- State the result for a positive trace-preserving linear map whose trace adjoint is Schwarz, without a Kraus or complete-positivity hypothesis.
- Quantify every maximum-rank stationary density matrix, exactly as Wolf does; do not silently replace it by one canonical witness.
- Represent `ρ⁻¹ᐟ²` on `supp(ρ)` without assuming that `ρ` is invertible on the ambient space, and include the zero-dimensional/support boundary honestly.
- Prove that the displayed weighted fixed-point set is a star algebra and supply a membership/equality theorem that identifies the formal carrier with Wolf's displayed set.
- Reduce or document the existing Kraus declarations as specializations; do not leave two source-facing APIs with incompatible hypotheses.
- Synchronize the Blueprint and numbering coverage, resolve the Corollary 6.7 paper-gap note, and run targeted Lean, `#print axioms`, forbidden-token, and Blueprint checks.

This issue is distinct from Corollary 6.6: the latter concerns the adjoint fixed-point corner `Q T*(Y) Q = Y`; this issue concerns the Schrödinger fixed-point space weighted by a maximum-rank stationary density.

### LINKED ISSUE #394: Wolf determinant extremality for positive trace-preserving maps
## Source

Wolf, Chapter 6, Theorem “Determinants”; local source `Notes/WolfNoteTexSource/ch06_spectral_properties.tex`, lines 351--407. Parent tracker: #38.

## Target

For a positive trace-preserving complex-linear map `T : M_d(ℂ) → M_d(ℂ)`:

1. `det T` is real and belongs to `[-1,1]`;
2. `|det T| = 1` iff `T` is unitary conjugation or unitary conjugation after ordinary matrix transposition;
3. unitary conjugation has determinant `1`; transposition has determinant `(-1)^{d(d-1)/2}`, hence determinant `-1` exactly when `⌊d/2⌋` is odd.

The existing completely-positive channel equality theorem is only the unitary branch and must remain a specialization, not the source-facing theorem.

## Required proof route

Follow Wolf: reality from conjugate-paired eigenvalues of a Hermiticity-preserving map; the modulus bound from the positive trace-preserving spectral-radius theorem; phase-only spectrum and recurrent powers give a positive trace-preserving inverse; extremality of pure states and the Hilbert--Schmidt isometry reduce to Wigner's theorem; finally compute the transpose parity in a Hermitian operator basis. Reuse the existing Wigner and transfer/determinant infrastructure rather than introducing an independent projective-classification argument.

## Acceptance criteria

- No complete-positivity or Kraus hypothesis in the headline.
- State the implicit positive-dimension boundary explicitly; do not let the `d=0` determinant convention produce a false classification.
- Include both unitary and transpose branches and the exact parity equivalence.
- Make the existing channel theorem a direct corollary where practical.
- Match Wolf's terminology and ordinary transpose notation, synchronize Blueprint/coverage, and run targeted axioms/bypass checks.

### PR DESCRIPTION
**Pull request by LionSR**
## Summary

- expand the undefined `\supp` command in the Corollary 6.7 resolution note to `\operatorname{supp}`
- replace the undefined Blueprint-only `\one` command in the determinant proof with the established `\Id` macro
- keep both repairs local and mathematical content unchanged

## Source faithfulness

Wolf Corollary 6.7 uses support notation at `Notes/WolfNoteTexSource/ch06_spectral_properties.tex`, lines 1503--1509, and the Wolf preamble defines `\supp` as `\operatorname{supp}`. The standalone paper-gap note now uses that exact expansion.

Wolf source lines 351--407 use `\one`, whose source preamble expansion is `\mathbb{1}`. Blueprint `src/macros/common.tex` defines the established `\Id` macro with the same expansion, so the Blueprint repair uses its existing identity notation rather than introducing another command.

## Reproduced regressions

- focused paper-gap compilation failed at line 70 with undefined control sequence `\supp`
- full `leanblueprint pdf` failed in `ch03_channel_representations_normal_forms_and_determinant.tex` at the identity equation with undefined control sequence `\one`
- the post-#404 main run [32679912392](https://github.com/LionSR/QICLean/actions/runs/32679912392) failed solely in the all-paper-gap build on the Corollary 6.7 note, confirming this PR is the required landed-CI repair

## Validation

After rebasing onto exact `daba92beb0a7de737ad3e6c907ba8641f95a343f`:

- `leanblueprint pdf` (316-page PDF, including the #404 positive-inverse additions)
- strict `texra-blueprint web`
- `texra-blueprint --root . paper-gaps build` (all 41 notes)
- `texra-blueprint paper-gaps check` (38 referenced slugs)
- `python3 scripts/blueprint_lean_sync.py --root . --ci` (2033 unique references / 2054 entries, 100 percent)
- full Blueprint `chktex`
- reader-facing prose check
- `git diff --check`
- exact-base `lake build QICLean` (9251 jobs) followed by `checkdecls` against this head generated 2033-entry declaration list

## Tracking

Follow-up document-build repairs to #400 / closed #392 and #401 / closed #394. This PR closes no leaf or tracking issue; chapter tracker #42 remains open.

### CODE REVIEW

**Comment by LionSR** [comment]
Independent exact-head review: **approved** for `6d636af41d6966d74a0fd110d523ece1ccb7baab`.

The two-line diff is the minimal source-faithful repair for the reproduced document-build regressions:

- `Notes/WolfNoteTexSource/preamble.tex` defines `\supp` as `\operatorname{supp}`, so expanding the unavailable standalone-note command preserves Wolf notation exactly.
- The Wolf preamble defines `\one` as `\mathbb{1}`, while the Blueprint macro surface already defines `\Id` with the same expansion; using `\Id` fixes the full Blueprint PDF without introducing a competing notation.

No mathematical statement or proof boundary changes. I verified the exact remote diff against current main, the post-#404 failed main run `32679912392`, and the full local evidence: 316-page `leanblueprint pdf`, strict web rendering, all 41 paper-gap PDFs, 38-slug reference check, Blueprint sync/checkdecls, full project build, chktex, prose, and diff checks.

Final exact-head hosted state: all applicable checks are terminal `SUCCESS`, the policy-only job is correctly skipped for this documentation diff, merge state is `CLEAN`, and GraphQL `reviewThreads(first:100)` reports zero threads with no pagination. No finding remains.
